#!/usr/bin/env python

import os
import re

problem = "ctp2"
microtask_number = 1
microtask_file = problem + "_mutask1_"

tasks = [
    ## 5 vertices
    'graphs/test00_5.graph',
    'graphs/test01_5.graph',
    'graphs/test02_5.graph',
    'graphs/test03_5.graph',
    'graphs/test04_5.graph',
    'graphs/test05_5.graph',
    'graphs/test06_5.graph',
    'graphs/test07_5.graph',
    'graphs/test08_5.graph',
    'graphs/test09_5.graph',
    ## 6 vertices
    'graphs/test00_6.graph',
    'graphs/test01_6.graph',
    'graphs/test02_6.graph',
    'graphs/test03_6.graph',
    'graphs/test04_6.graph',
    'graphs/test05_6.graph',
    'graphs/test06_6.graph',
    'graphs/test07_6.graph',
    'graphs/test08_6.graph',
    'graphs/test09_6.graph',
    ## 7 vertices
    #'graphs/test00_7.graph',
    #'graphs/test01_7.graph',
    #'graphs/test02_7.graph',
    #'graphs/test03_7.graph',
    #'graphs/test04_7.graph',
    #'graphs/test05_7.graph',
    #'graphs/test06_7.graph',
    #'graphs/test07_7.graph',
    #'graphs/test08_7.graph',
    #'graphs/test09_7.graph',
    ## 8 vertices
    #'graphs/test00_8.graph',
    #'graphs/test01_8.graph',
    #'graphs/test02_8.graph',
    #'graphs/test03_8.graph',
    #'graphs/test04_8.graph',
    #'graphs/test05_8.graph',
    #'graphs/test06_8.graph',
    #'graphs/test07_8.graph',
    #'graphs/test08_8.graph',
    #'graphs/test09_8.graph',
    ## 9 vertices
    #'graphs/test00_9.graph',
    #'graphs/test01_9.graph',
    #'graphs/test02_9.graph',
    #'graphs/test03_9.graph',
    #'graphs/test04_9.graph',
    #'graphs/test05_9.graph',
    #'graphs/test06_9.graph',
    #'graphs/test07_9.graph',
    #'graphs/test08_9.graph',
    #'graphs/test09_9.graph',
    ## 10 vertices
    #'graphs/test00_10.graph',
    #'graphs/test01_10.graph',
    #'graphs/test02_10.graph',
    #'graphs/test03_10.graph',
    #'graphs/test04_10.graph',
    #'graphs/test05_10.graph',
    #'graphs/test06_10.graph',
    #'graphs/test07_10.graph',
    #'graphs/test08_10.graph',
    #'graphs/test09_10.graph',
    ## 11 vertices
    #'graphs/test00_11.graph',
    #'graphs/test01_11.graph',
    #'graphs/test02_11.graph',
    #'graphs/test03_11.graph',
    #'graphs/test04_11.graph',
    #'graphs/test05_11.graph',
    #'graphs/test06_11.graph',
    #'graphs/test07_11.graph',
    #'graphs/test08_11.graph',
    #'graphs/test09_11.graph',
    ## 15 vertices
    #'graphs/test00_15.graph',
    #'graphs/test01_15.graph',
    #'graphs/test02_15.graph',
    #'graphs/test03_15.graph',
    #'graphs/test04_15.graph',
    #'graphs/test05_15.graph',
    #'graphs/test06_15.graph',
    #'graphs/test07_15.graph',
    #'graphs/test08_15.graph',
    #'graphs/test09_15.graph',
    ## 19 vertices
    #'graphs/test00_19.graph',
    #'graphs/test01_19.graph',
    #'graphs/test02_19.graph',
    #'graphs/test03_19.graph',
    #'graphs/test04_19.graph',
    #'graphs/test05_19.graph',
    #'graphs/test06_19.graph',
    #'graphs/test07_19.graph',
    #'graphs/test08_19.graph',
    #'graphs/test09_19.graph',
]

policies = [
    #"optimal direct",
    #"greedy direct",
    #"random direct",
    #"greedy rollout",
    #"random rollout",
    "greedy uct",
    #"random uct",
    #"greedy ao3",
    "greedy ao3",
    #"greedy ao4",
    #"random ao4",
]

rollout_widths = [ 10, 100 ]
uct_widths = [ 1, 5, 10, 50, 100, 500, 1000, 5000, 10000 ]
uct_parameters = [ 0, -10, -25, -50, -100, -250, -500, -1000 ]
ao_widths = [ 1, 5, 10, 50, 100, 500, 1000, 5000 ]
ao_depths = [ 1, 5, 10, 50, 100 ]
ao_parameters = [ 0.5 ]

def open_file():
    f = open(microtask_file + str(microtask_number), 'w')
    f.write('#!/usr/bin/env python\n')
    f.write('import os\n')
    f.write('output = open("output.' + microtask_file + str(microtask_number) + '", "w")\n')
    f.write('cmd = "./' + problem + '  -f -a 0 -h 1 ')
    return f

def close_file(f):
    global microtask_number
    f.write('"\n')
    f.write('output.write("cmd=" + cmd + "\\n")\n')
    f.write('output.close()\n')
    f.write('os.system(cmd + " >> output.' + microtask_file + str(microtask_number) + '")\n')
    f.close()
    microtask_number += 1

for t in tasks:
    base = os.path.basename(t)
    depth = re.split("[_\.]", base)[1]
    for p in policies:
        if p == "optimal direct" or p == "greedy direct" or p == "random direct":
            f = open_file()
            f.write(t + ' ' + p)
            close_file(f)
        elif p == "greedy rollout" or p == "random rollout":
            for width in rollout_widths:
                for nesting in range(1, 2):
                    f = open_file()
                    f.write(t + ' ' + p + ' ')
                    f.write(str(width) + ' ' + str(depth) + ' 0 ' + str(nesting))
                    close_file(f)
        elif p == "greedy uct" or p == "random uct":
            for width in uct_widths:
                for par in uct_parameters:
                    f = open_file()
                    f.write(t + ' ' + p + ' ')
                    f.write(str(width) + ' ' + str(depth) + ' ' + str(par))
                    close_file(f)
        elif p == "greedy ao3" or p == "random ao3" or p == "greedy ao4" or p == "random ao4":
            for width in ao_widths:
                for par in ao_parameters:
                    f = open_file()
                    f.write(t + ' ' + p + ' ')
                    f.write(str(width) + ' ' + str(depth) + ' ' + str(par) + ' 100')
                    close_file(f)

