#!/usr/bin/env python

problem = "sailing"
microtask_number = 1
microtask_file = problem + "_mutask_"

tasks = [
    '-s 0 10',
    '-s 0 50',
    '-s 0 100',
]

policies = [
    "optimal direct",
    "greedy direct",
    "random direct",
    #"greedy rollout",
    #"random rollout",
    "greedy uct",
    "random uct",
    "greedy ao3",
    "random ao3",
    "greedy ao4",
    "random ao4",
]

rollout_widths = [ 10, 100 ]
uct_widths = [ 10, 25, 50, 100, 250, 500, 1000, 2500, 5000, 10000 ]
uct_parameters = [ 0, -5, -10, -15, -20, -25, -30 ]
ao_widths = [ 10, 25, 50, 100, 250, 500, 1000, 5000 ]
ao_parameters = [ 0.5 ]

def open_file():
    f = open(microtask_file + str(microtask_number), 'w')
    f.write('#!/usr/bin/env python\n')
    f.write('import os\n')
    f.write('output = open("output.' + microtask_file + str(microtask_number) + '", "w")\n')
    f.write('cmd = "./' + problem + '  -f -a 1 -h 1 ')
    return f

def close_file(f):
    global microtask_number
    f.write('"\n')
    f.write('output.write("cmd=" + cmd + "\\n")\n')
    f.write('output.close()\n')
    f.write('os.system(cmd + " >> output.' + microtask_file + str(microtask_number) + '")\n')
    f.close()
    microtask_number += 1

for t in tasks:
    for p in policies:
        if p == "optimal direct" or p == "greedy direct" or p == "random direct":
            f = open_file()
            f.write(t + ' ' + p)
            close_file(f)
        elif p == "greedy rollout" or p == "random rollout":
            for width in rollout_widths:
                    for nesting in range(1, 2):
                        f = open_file()
                        f.write(t + ' ' + p + ' ')
                        f.write(str(width) + ' 50 0 ' + str(nesting))
                        close_file(f)
        elif p == "greedy uct" or p == "random uct":
            for width in uct_widths:
                    for par in uct_parameters:
                        f = open_file()
                        f.write(t + ' ' + p + ' ')
                        f.write(str(width) + ' 50 ' + str(par))
                        close_file(f)
        elif p == "greedy ao3" or p == "random ao3" or p == "greedy ao4" or p == "random ao4":
            for width in ao_widths:
                    for par in ao_parameters:
                        f = open_file()
                        f.write(t + ' ' + p + ' ')
                        f.write(str(width) + ' 50 ' + str(par))
                        close_file(f)

