#!/usr/bin/env python

import os
import re

problem = "ctp3"
microtask_number = 1
microtask_file = problem + "_mutask3_"

tasks = [
    ## 20 vertices
    'AAAI-graphs/test00_20_T.graph',
    'AAAI-graphs/test01_20_T.graph',
    'AAAI-graphs/test02_20_T.graph',
    'AAAI-graphs/test03_20_T.graph',
    'AAAI-graphs/test04_20_T.graph',
    'AAAI-graphs/test05_20_T.graph',
    'AAAI-graphs/test06_20_T.graph',
    'AAAI-graphs/test07_20_T.graph',
    'AAAI-graphs/test08_20_T.graph',
    'AAAI-graphs/test09_20_T.graph',
]

policies = [
    "random ao3",
    "optimistic ao3",
]

rollout_widths = [ 10, 100 ]
uct_widths = [ 1, 5, 10, 50, 100, 500, 1000, 5000, 10000 ]
uct_parameters = [ 0, -10, -25, -50, -100, -250, -500, -1000 ]
ao_widths = [ 100, 500, 1000 ]
ao_parameters = [ 0.9 ]

def open_file():
    f = open(microtask_file + str(microtask_number), 'w')
    f.write('#!/usr/bin/env python\n')
    f.write('import os\n')
    f.write('output = open("output.' + microtask_file + str(microtask_number) + '", "w")\n')
    f.write('cmd = "./' + problem + '  -f -a 0 -h 1 ')
    return f

def close_file(f):
    global microtask_number
    f.write('"\n')
    f.write('output.write("cmd=" + cmd + "\\n")\n')
    f.write('output.close()\n')
    f.write('os.system(cmd + " >> output.' + microtask_file + str(microtask_number) + '")\n')
    f.close()
    microtask_number += 1

for t in tasks:
    base = os.path.basename(t)
    depth = re.split("[_\.]", base)[1]
    for p in policies:
        if p == "optimal direct" or p == "greedy direct" or p == "random direct":
            f = open_file()
            f.write(t + ' ' + p)
            close_file(f)
        elif p == "greedy rollout" or p == "random rollout":
            for width in rollout_widths:
                for nesting in range(1, 2):
                    f = open_file()
                    f.write(t + ' ' + p + ' ')
                    f.write(str(width) + ' ' + str(depth) + ' 0 ' + str(nesting))
                    close_file(f)
        elif p == "greedy uct" or p == "random uct":
            for width in uct_widths:
                for par in uct_parameters:
                    f = open_file()
                    f.write(t + ' ' + p + ' ')
                    f.write(str(width) + ' ' + str(depth) + ' ' + str(par))
                    close_file(f)
        elif p == "optimistic ao3" or p == "optimistic ao4" or p == "greedy ao3" or p == "random ao3" or p == "greedy ao4" or p == "random ao4":
            for width in ao_widths:
                for par in ao_parameters:
                    f = open_file()
                    f.write(t + ' ' + p + ' ')
                    f.write(str(width) + ' ' + str(depth) + ' ' + str(par) + ' 500')
                    close_file(f)

