#!/usr/bin/env python

import os
import re

problem = "sailing"
extra_parameters = ""
task_number = 21

microtask_number = 1
microtask_file = problem + "_mutask" + str(task_number) + "_"

tasks = [
    50,
    100,
]

policies = [
    "random uct",
    #"greedy uct",
    "random aot",
    #"greedy aot",
]

rollout_widths = [ 10, 100 ]
uct_widths = [ 10, 50, 100, 500, 1000, 5000, 10000 ]
uct_parameters = [ 0 ]
aot_widths = [ 10, 50, 100, 500, 1000 ]
aot_random_widths = [ 10, 50, 100, 500, 1000, 5000, 10000, 50000 ]
aot_parameters = [ 0.5 ]
aot_nexp = [ 1, .5, .1 ]

def open_file():
    f = open(microtask_file + str(microtask_number), 'w')
    f.write('#!/usr/bin/env python\n')
    f.write('import os\n')
    f.write('output = open("output.' + microtask_file + str(microtask_number) + '", "w")\n')
    f.write('cmd = "./' + problem + ' -h 1 -s 0 ' + extra_parameters + ' ')
    return f

def close_file(f):
    global microtask_number
    f.write('"\n')
    f.write('output.write("cmd=" + cmd + "\\n")\n')
    f.write('output.close()\n')
    f.write('os.system(cmd + " >> output.' + microtask_file + str(microtask_number) + '")\n')
    f.close()
    microtask_number += 1

for t in tasks:
    task = str(t)
    depth = 2*t
    for p in policies:
        if p == "optimal direct" or p == "greedy direct" or p == "random direct":
            f = open_file()
            f.write(task + ' ' + p)
            close_file(f)
        elif p == "greedy rollout" or p == "random rollout":
            for width in rollout_widths:
                for nesting in range(1, 2):
                    f = open_file()
                    f.write(task + ' ' + p + ' ')
                    f.write(str(width) + ' ' + str(depth) + ' 0 ' + str(nesting))
                    close_file(f)
        elif p == "random uct" or p == "greedy uct":
            for width in uct_widths:
                for par in uct_parameters:
                    f = open_file()
                    f.write(task + ' ' + p + ' ')
                    f.write(str(width) + ' ' + str(depth) + ' ' + str(par))
                    close_file(f)
        elif p == "random aot" or p == "greedy aot":
            for width in aot_widths:
                for par in aot_parameters:
                    for factor in aot_nexp:
                        nexp = int(factor * width)
                        if nexp > 0:
                            f = open_file()
                            f.write(task + ' ' + p + ' ')
                            f.write(str(width) + ' ' + str(depth) + ' ' + str(par) + ' ' + str(nexp))
                            close_file(f)
        elif p == "random aot*" or p == "greedy aot*":
            for width in aot_widths:
                for par in aot_parameters:
                    for factor in aot_nexp:
                        nexp = int(factor * width)
                        if nexp > 0:
                            f = open_file()
                            f.write(task + ' ' + p + ' ')
                            f.write(str(width) + ' ' + str(depth) + ' ' + str(par) + ' ' + str(nexp))
                            close_file(f)
        elif p == "random aot-random" or p == "greedy aot-random":
            for width in aot_random_widths:
                for par in aot_parameters:
                    for factor in aot_nexp:
                        nexp = int(factor * width)
                        if nexp > 0:
                            f = open_file()
                            f.write(task + ' ' + p + ' ')
                            f.write(str(width) + ' ' + str(depth) + ' ' + str(par) + ' ' + str(nexp))
                            close_file(f)
        elif p == "heuristic aot-value":
            for width in aot_widths:
                for par in aot_parameters:
                    for factor in aot_nexp:
                        nexp = int(factor * width)
                        if nexp > 0:
                            f = open_file()
                            f.write('-h 12 ' + task + ' ' + p + ' ')
                            f.write(str(width) + ' ' + str(depth) + ' ' + str(par) + ' ' + str(nexp))
                            close_file(f)

