#!/usr/bin/env python

problem = "sailing"
microtask_number = 1
microtask_file = problem + "_mutask2_"

tasks = [
    '5',
    '10',
    '25',
    '50',
    '75',
    '100',
]

policies = [
    "random uct",
    "greedy uct",
    "random aot",
    "greedy aot",
]

rollout_widths = [ 10, 100 ]
uct_widths = [ 10, 25, 50, 100, 250, 500, 1000, 2500, 5000, 10000 ]
uct_parameters = [ 0 ]
ao_widths = [ 10, 50, 100, 500, 1000, 5000 ]
ao_parameters = [ 0.5 ]

def open_file():
    f = open(microtask_file + str(microtask_number), 'w')
    f.write('#!/usr/bin/env python\n')
    f.write('import os\n')
    f.write('output = open("output.' + microtask_file + str(microtask_number) + '", "w")\n')
    f.write('cmd = "./' + problem + '  -f -a 0 -h 1 -s 0 ')
    return f

def close_file(f):
    global microtask_number
    f.write('"\n')
    f.write('output.write("cmd=" + cmd + "\\n")\n')
    f.write('output.close()\n')
    f.write('os.system(cmd + " >> output.' + microtask_file + str(microtask_number) + '")\n')
    f.close()
    microtask_number += 1

for t in tasks:
    for p in policies:
        if p == "optimal direct" or p == "greedy direct" or p == "random direct":
            f = open_file()
            f.write(t + ' ' + p)
            close_file(f)
        elif p == "random rollout" or p == "greedy rollout":
            for width in rollout_widths:
                    for nesting in range(1, 2):
                        f = open_file()
                        f.write(t + ' ' + p + ' ')
                        f.write(str(width) + ' ' + str(t) + ' 0 ' + str(nesting))
                        close_file(f)
        elif p == "random uct" or p == "greedy uct":
            for width in uct_widths:
                    for par in uct_parameters:
                        f = open_file()
                        f.write(t + ' ' + p + ' ')
                        f.write(str(width) + ' ' + str(t) + ' ' + str(par))
                        close_file(f)
        elif p == "random aot" or p == "greedy aot":
            for width in ao_widths:
                    for par in ao_parameters:
                        f = open_file()
                        f.write(t + ' ' + p + ' ')
                        f.write(str(width) + ' ' + str(t) + ' ' + str(par) + ' 100')
                        close_file(f)
        elif p == "random aot*" or p == "greedy aot*":
            for width in ao_widths:
                    for par in ao_parameters:
                        f = open_file()
                        f.write(t + ' ' + p + ' ')
                        f.write(str(width) + ' ' + str(t) + ' ' + str(par) + ' 100')
                        close_file(f)

